asn = 47065
router_id = "10.0.0.1"
listen_port = 1709
listen_addr = [ "0.0.0.0" ]

prefixes = [ 
{ id = 1, prefix = "184.164.250.0/24", asn = 47065 },
{ id = 2, prefix = "184.164.251.0/24", asn = 47065 },
]

sites = [
{ id = 5, name = "amsterdam01", neighbor = "100.69.128.1", asn = 47065 },
{ id = 16, name = "clemson01", neighbor = "100.80.128.1", asn = 47065 },
{ id = 6, name = "gatech01", neighbor = "100.70.128.1", asn = 47065 },
{ id = 9, name = "grnet01", neighbor = "100.73.128.1", asn = 47065 },
{ id = 2, name = "isi01", neighbor = "100.66.128.1", asn = 47065 },
{ id = 14, name = "neu01", neighbor = "100.78.128.1", asn = 47065 },
{ id = 2, name = "isi01", neighbor = "100.66.128.1", asn = 47065 },
{ id = 14, name = "neu01", neighbor = "100.78.128.1", asn = 47065 },
{ id = 19, name = "saopaulo01", neighbor = "100.83.128.1", asn = 47065 },
{ id = 1, name = "seattle01", neighbor = "100.65.128.1", asn = 47065 },
{ id = 7, name = "ufmg01", neighbor = "100.71.128.1", asn = 47065 },
{ id = 17, name = "utah01", neighbor = "100.81.128.1", asn = 47065 },
{ id = 10, name = "uw01", neighbor = "100.74.128.1", asn = 47065 },
{ id = 25, name = "vtramsterdam", neighbor = "100.89.128.1", asn = 47065 },
{ id = 24, name = "vtratlanta", neighbor = "100.88.128.1", asn = 47065 },
{ id = 40, name = "vtrbangalore", neighbor = "100.104.128.1", asn = 47065 },
{ id = 30, name = "vtrchicago", neighbor = "100.94.128.1", asn = 47065 },
{ id = 35, name = "vtrdallas", neighbor = "100.99.128.1", asn = 47065 },
{ id = 41, name = "vtrdelhi", neighbor = "100.105.128.1", asn = 47065 },
{ id = 28, name = "vtrfrankfurt", neighbor = "100.92.128.1", asn = 47065 },
{ id = 54, name = "vtrhonolulu", neighbor = "100.118.128.1", asn = 47065 },
{ id = 49, name = "vtrjohannesburg", neighbor = "100.113.128.1", asn = 47065 },
{ id = 44, name = "vtrlondon", neighbor = "100.108.128.1", asn = 47065 },
{ id = 42, name = "vtrlosangelas", neighbor = "100.106.128.1", asn = 47065 },
{ id = 38, name = "vtrmadrid", neighbor = "100.102.128.1", asn = 47065 },
{ id = 52, name = "vtrmanchester", neighbor = "100.116.128.1", asn = 47065 },
{ id = 47, name = "vtrmelbourne", neighbor = "100.111.128.1", asn = 47065 },
{ id = 36, name = "vtrmexico", neighbor = "100.100.128.1", asn = 47065 },
{ id = 23, name = "vtrmiami", neighbor = "100.87.128.1", asn = 47065 },
{ id = 45, name = "vtrmumbai", neighbor = "100.109.128.1", asn = 47065 },
{ id = 34, name = "vtrnewyork", neighbor = "100.98.128.1", asn = 47065 },
{ id = 50, name = "vtrosaka", neighbor = "100.114.128.1", asn = 47065 },
{ id = 31, name = "vtrparis", neighbor = "100.95.128.1", asn = 47065 },
{ id = 51, name = "vtrsantiago", neighbor = "100.115.128.1", asn = 47065 },
{ id = 48, name = "vtrsaopaulo", neighbor = "100.112.128.1", asn = 47065 },
{ id = 29, name = "vtrseattle", neighbor = "100.93.128.1", asn = 47065 },
{ id = 46, name = "vtrseoul", neighbor = "100.110.128.1", asn = 47065 },
{ id = 43, name = "vtrsilicon", neighbor = "100.107.128.1", asn = 47065 },
{ id = 32, name = "vtrsingapore", neighbor = "100.96.128.1", asn = 47065 },
{ id = 39, name = "vtrstockholm", neighbor = "100.103.128.1", asn = 47065 },
{ id = 27, name = "vtrsydney", neighbor = "100.91.128.1", asn = 47065 },
{ id = 53, name = "vtrtelaviv", neighbor = "100.117.128.1", asn = 47065 },
{ id = 26, name = "vtrtokyo", neighbor = "100.90.128.1", asn = 47065 },
{ id = 37, name = "vtrtoronto", neighbor = "100.101.128.1", asn = 47065 },
{ id = 33, name = "vtrwarsaw", neighbor = "100.97.128.1", asn = 47065 },
{ id = 11, name = "wisc01", neighbor = "100.75.128.1", asn = 47065 },
]
